### PR TITLE
fix buy item dialog

### PR DESCRIPTION
**Pull request by VladGrant**
Fixes the problem with the dialog of "Buy Item" dialog due to overzealously removing a value dereference.

### CODE REVIEW

**Comment by VladGrant** [comment]
I added the basic functionality into this PR as well.

**Comment by VladGrant** [comment]
Caught up to the new version, with the reworked method for getting change.

**Comment by DanielBoettner** [comment]
@VladGrant 
Could you check if you can include your changes into https://github.com/jopeek/fvtt-loot-sheet-npc-5e/pull/202 ?

I was planning to add a selling functionality but didn't have the time.

I can also try to include your code. But first would like to get the above PR  merged.

**Comment by VladGrant** [comment]
Honestly, I found that the functionality of selling in Merchant Sheet to be done a lot better, I would just ask the author to see if his code could be used here as well. This PR should probably get closed out, unless someone feels very strongly about these changes.

https://github.com/whelan/fvtt-merchant-sheet-npc

**Comment by DanielBoettner** [comment]
Thank you for your reply. I know jopeek closed the issue already. I still wanted to add a reply.

Good idea with the merchant sheet, I think could even be a good idea to invite the merchant sheet developer to collaborate.

My refactoring modularized the code quite a bit.
I think, it should now be easier to add features. 

And a module like this could profit from several people beeing able to help out fixing bugs and generally beeing involved.

Beeing that it is open source work and no one gets paid contributing their time.

**Pull request closed without merging**
