### PR TITLE
Reformat code (in preparation for future changes)

### PR DESCRIPTION
**Pull request by Varriount**
- Reformat code
- Remove commented-out code

### CODE REVIEW

**Comment by jopeek** [comment]
There’s a rather substantial code change coming from a contributor that will render these changes either unnecessary or having to be redone. I will hold off on this pull request for the time being.

**Comment by Varriount** [comment]
Huh, thanks for letting me know! I actually just started on my own significant refactoring (much more than is what is in this PR), so I'll hold off for now.

**Comment by DanielBoettner** [comment]
I will create the PR now.

Could be that the release process needs some final touches.

**Comment by DanielBoettner** [comment]
@Varriount 
Please feel free to take a look at https://github.com/jopeek/fvtt-loot-sheet-npc-5e/pull/202
A downloadable zip is linked in the PR.

**Comment by jopeek** [comment]
Closed due to major refactor.

**Pull request closed without merging**
