### PR TITLE
Add selling to merchants

### PR DESCRIPTION
**Pull request by VladGrant**
This should enable dropping on a merchant sheet to sell at half price.

### CODE REVIEW

**Comment by Streyder** [comment]
This uses the old, broken coin conversion system. See https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/126
So this still needs a fix eventually

This should also get a setting for the sales price instead of it being fixed at 50%

**Comment by VladGrant** [comment]
I'll get that worked in but I have a bunch of changes and cleanup, especially for #106 (which is standardizing the data model more so than actually anything functional) so this PR is going to end up being a lot larger than it currently is. I'll work in your way of doing change into it as well to fit. I foresee a lot of collisions between these PRs however.

**Comment by Streyder** [comment]
That is true. We should think about a central point to do any kind of currency conversions. My code can be a basis for that, but it can also easily be made more general and split into multiple functions like:

- Convert Currency from X to Y
- Compensate negative currency with other currency
- Exchange fractions of currency with "change" of lower currencies.

If we split it like that it might be easy to rework a lot of code.

Also: 0.8 will bring a major overhaul of the datamodel and will most likely require quit a few changes.

**Comment by VladGrant** [comment]
I thought the currency data model was based on systems, not core, so I just
matched that up.

I actually mostly model my changes after what the PF1e version of
lootsheets did to fix up some  weird idiosyncracies.

**Comment by Streyder** [comment]
Well every game system has its own currency system. Generalizing this would be awesome but I am too much of a novice with Foundry to make that happen

**Comment by VladGrant** [comment]
I have added the selling functionality in another PR that includes a fix for the data remodel (to fit the new dnd5e system) #129 .

**Pull request closed without merging**
